export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS"
export const GET_TODO_LIST_SUCCESS = "GET_TODO_LIST_SUCCESS"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const IS_LOADING = "IS_LOADING"
export const IS_ERROR = "IS_ERROR"





